export const LESSON_LOCKED = 'Még nincs feloldva'
export const LESSON_UPCOMING = 'Soron következő lecke'
export const LESSON_COMPLETED = 'Már megtanult lecke'
export const LESSON_NOT_IN_TIER = 'Ebben a körben nincs ilyen lecke'

export const LEARN_BUTTON = 'Tanulás'
export const REVIEW_BUTTON = 'Ismétlés'
export const LESSON_SELECT_TITLE = 'Leckeválasztó'
export const UPCOMING_LESSON_LABEL = 'KÖVETKEZŐ'
export const CHARACTER_AMOUNT_LABEL = 'karakter'
